services:
  recorder:
    build: .
    environment:
      PYTHONUNBUFFERED: 1
      SOURCE_PATH: /data/bbb_sunflower_1080p_30fps_normal.mp4
      SOURCE_FPS: 30
      RECORDS_BASEPATH: /data
      RECORDS_HISTSIZE: 10
    volumes:
      - ./data:/data
    ports:
      - 127.0.0.1:8080:8080
